import turtle

turtle.forward(50)
turtle.right(120)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.right(180)
turtle.forward(50)
turtle.left(90)
turtle.pendown()
turtle.forward(50)
turtle.penup()
turtle.left(30)
turtle.forward(30)
turtle.left(90)
turtle.pendown()
turtle.forward(50)
turtle.left(90)
turtle.forward(30)
turtle.left(180)
turtle.forward(30)
turtle.left(90)
turtle.forward(20)

turtle.penup()
turtle.goto(100,10)
turtle.pendown()
turtle.forward(50)
turtle.penup()
turtle.goto(90,0)
turtle.pendown()
turtle.forward(70)
turtle.penup()
turtle.goto(130,-40)
turtle.pendown()
turtle.circle(10)
turtle.penup()
turtle.goto(180,10)
turtle.pendown()
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(180)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.goto(130,-80)
turtle.pendown()
turtle.forward(50)
turtle.left(90)
turtle.forward(50)

turtle.penup()
turtle.goto(300,-40)
turtle.pendown()
turtle.circle(30)
turtle.penup()
turtle.goto(350,20)
turtle.pendown()
turtle.right(90)
turtle.forward(100)
turtle.penup()
turtle.goto(300,-80)
turtle.pendown()
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)









turtle.exitonclick()
